config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
    resources :categories do

    end
    resources :locations
  end

  # 收藏／取消收藏工作
  resources :jobs do
    member do
      post :favorites #因与下面的favorite同名，出现routes错误，此处改名处理
      post :unfavorite
    end
    collection do
      get :search
    end
    resources :resumes
  end



  # 我收藏的工作
  namespace :favorite do #此处即为上面所说变量重名的问题
    resources :jobs
  end

  # 我的讨论组和我的文章
  namespace :account do
    resources :groups do
      resources :posts
    end
    resources :posts
    resources :resumes
    resources :votes
    resources :comments
  end

  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      # member do
        # post :upvote
        # post :downvote
      #   post "upvote" => "posts#upvote"
      #   post "downvote" => "posts#downvote"
      # end
      resources :comments do
        # member do
        #   post :like
        #   post :unlike
        # end
      end
    end
  end
  # resources :posts


  resources :posts do
    member do
      # post :upvote
      # post :downvote
      post "upvote" => "posts#upvote"
      post "downvote" => "posts#downvote"
    end
  end

  resources :comments do
    member do
      post :like
      post :unlike
    end
  end

  root 'welcome#index'
end

app/models/job.rb
class Job < ApplicationRecord
  # 标题不能为空
  validates :title, presence: true
  #薪资不能为空，最低底薪大于0
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
  # 重构重复代码／公开
  scope :published, -> { where(is_hidden: false) }
  # 自动查找5个职位数据
  scope :random5, -> { limit(5).order("RANDOM()") }
  # 重构重复代码／最近排序
  scope :recent, -> { order('created_at DESC') }
  scope :wage1, -> { where('wage_lower_bound <= 5 or wage_upper_bound <= 5') }
  scope :wage2, -> { where('wage_lower_bound between 5 and 10 or wage_upper_bound between 5 and 10') }
  scope :wage3, -> { where('wage_lower_bound between 10 and 15 or wage_upper_bound between 10 and 15') }
  scope :wage4, -> { where('wage_lower_bound between 15 and 25 or wage_upper_bound between 15 and 25') }
  scope :wage5, -> { where('wage_lower_bound >= 25 or wage_upper_bound >= 25') }

  # has_many :resumes
  has_many :resumes, dependent: :destroy

  # 收藏职位
  has_many :job_favorites
  has_many :collectors, through: :job_favorites, source: :user

  belongs_to :user
  # 职位类别
  belongs_to :category

  # 工作地点
  belongs_to :location

  # 公开职位
  def publish!
    self.is_hidden = false
    self.save
  end

  # 隐匿职位
  def hide!
    self.is_hidden = true
    self.save
  end

  before_validation :generate_friendly_id, :on => :create

  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  # 需要登录的操作
  before_action :authenticate_user!
  # 需要admin权限
  before_action :require_is_admin
  before_action :find_job_and_check_permission , only: [:edit, :update]
  # 套用管理界面样式
  layout "admin"

  def show
    @job = Job.find_by_friendly_id!(params[:id])
  end

  # def index
  #   @jobs = Job.all
  #   @categorys = Category.all
  #   @locations = Location.all
  # end

  def index
    @locations = Location.all
    @categorys = Category.all

    # 判断是否筛选城市 #
    if params[:location].present?
      @location = params[:location]
      @location_id = Location.find_by(name: @location)

      if @location == '所有城市'
        @jobs = Job.where(:user => current_user).recent.paginate(:page => params[:page], :per_page => 10)
      else
        @jobs = Job.where(:user => current_user, :location_id => @location_id).recent.paginate(:page => params[:page], :per_page => 10)
      end

    # 判断是否筛选职位类型 #
    elsif params[:category].present?
      @category = params[:category]
      @category_id = Category.find_by(name: @category)

      if @category == '所有类型'
        @jobs = Job.where(:user => current_user).recent.paginate(:page => params[:page], :per_page => 10)
      else
        @jobs = Job.where(:user => current_user, :category => @category_id).recent.paginate(:page => params[:page], :per_page => 10)
      end

    # 判断是否筛选薪水 #
    elsif @jobs = case params[:order]
        when 'by_lower_bound'
          Job.where(:user => current_user).order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 10)
        when 'by_upper_bound'
          Job.where(:user => current_user).order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 10)
        else
          Job.where(:user => current_user).recent.paginate(:page => params[:page], :per_page => 10)
    end

    # 预设显示所有公开职位 #
    else
      @jobs = Job.where(:user => current_user).published.recent.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def new
    @job = Job.new
    @categorys = Category.all
    @locations = Location.all
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new, notice: '职位创建成功。'
    end
  end

  def edit
    @job = Job.find_by_friendly_id!(params[:id])
    @categorys = Category.all
    @locations = Location.all
  end

  def update
    @job = Job.find_by_friendly_id!(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: '职位修改成功。'
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find_by_friendly_id!(params[:id])

    @job.destroy

    redirect_to admin_jobs_path, notice: '职位已删除。'
  end

 def publish
    @job = Job.find_by_friendly_id!(params[:id])
    @job.publish!

    redirect_to :back, notice: '职位已公开。'
  end

  def hide
    @job = Job.find_by_friendly_id!(params[:id])

    @job.hide!

    redirect_to :back, notice: '职位已隐藏。'
  end


  private

  def find_job_and_check_permission
    @job = Job.find_by_friendly_id!(params[:id])

    if @job.user != current_user
      redirect_to root_path, alert: "你没有权限进行此操作。"
    end
  end

  def job_params
    params.require(:job).permit(:title, :description, :company, :category_id, :location_id, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/favorite/jobs_controller.rb
class Favorite::JobsController < ApplicationController

  before_action :authenticate_user!
  # def index
  #   @jobs = current_user.favorite_jobs #列出当前用户收藏的所有工作
  #
  # end

  def index
    @user = current_user
    @job_favorites = JobFavorite.where(:user => @user).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # 需要登录的操作
  before_action :authenticate_user!, only: [:favorites, :unfavorite]
  before_action :validate_search_key, only: [:search]

  # def index
  #
  #   @jobs = case params[:order]
  #     when 'by_lower_bound'
  #       Job.published.order('wage_lower_bound DESC')
  #     when 'by_upper_bound'
  #       Job.published.order('wage_upper_bound DESC')
  #     else
  #       Job.published.recent
  #   end
  #
  # end

  def index
    @locations = Location.all
    @categorys = Category.all

    # 随机推荐五个职位 #
    @suggests = Job.published.random5

    # 判断是否筛选城市 #
    if params[:location].present?
      @location = params[:location]
      @location_id = Location.find_by(name: @location)

      if @location == '所有城市'
        @jobs = Job.published.recent.paginate(:page => params[:page], :per_page => 5)
      else
        @jobs = Job.where(:location => @location_id).published.recent.paginate(:page => params[:page], :per_page => 5)
      end

    # 判断是否筛选职位类型 #
    elsif params[:category].present?
      @category = params[:category]
      @category_id = Category.find_by(name: @category)

      if @category == '所有类型'
        @jobs = Job.published.recent.paginate(:page => params[:page], :per_page => 5)
      else
        @jobs = Job.where(:category => @category_id).published.recent.paginate(:page => params[:page], :per_page => 5)
      end

    # 判断是否筛选薪水 #
    elsif params[:wage].present?
      @wage = params[:wage]
      if @wage == '5k以下'
        @jobs = Job.wage1.published.recent.paginate(:page => params[:page], :per_page => 5)
      elsif @wage == '5~10k'
        @jobs = Job.wage2.published.recent.paginate(:page => params[:page], :per_page => 5)
      elsif @wage == '10~15k'
        @jobs = Job.wage3.published.recent.paginate(:page => params[:page], :per_page => 5)
      elsif @wage == '15~25k'
        @jobs = Job.wage4.published.recent.paginate(:page => params[:page], :per_page => 5)
      else
        @jobs = Job.wage5.published.recent.paginate(:page => params[:page], :per_page => 5)
      end

    # elsif @jobs = case params[:order]
    #     when 'by_lower_bound'
    #       Job.published.order('wage_lower_bound DESC')
    #     when 'by_upper_bound'
    #       Job.published.order('wage_upper_bound DESC')
    #     else
    #       Job.published.recent
    # end

    # 预设显示所有公开职位 #
    else
      @jobs = Job.published.recent.paginate(:page => params[:page], :per_page => 5)
    end
  end

  def show
    @job = Job.find_by_friendly_id!(params[:id])
    @category = @job.category

    # 随机推荐五个相同类型的职位（去除当前职位） #
    @sames = Job.where(:is_hidden => false, :category => @job.category).where.not(:id => @job.id ).random5
    # 搜索该用户投递此职位的简历数量 #
    @resumes = Resume.where(:job => @job, :user => current_user)
    if @job.is_hidden
      redirect_to root_path, alert: "此职位暂未开放。"
    end
  end


  def search
      if @query_string.present?
        # search_result = Job.ransack(@search_criteria).result(:distinct => true)
        search_result = Job.joins(:location).ransack(@search_criteria).result(:distinct => true)
        @jobs = search_result.published.paginate(:page => params[:page], :per_page => 5 )
        @suggests = Job.published.random5
      end
    end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to jobs_path
  end

  # 隐藏／显示职位提示
  # def show
  #   @job = Job.find(params[:id])
  #
  #   if @job.is_hidden
  #     flash[:warning] = "This Job already archieved"
  #     redirect_to root_path
  #   end
  # end

  def favorites
    @job = Job.find_by_friendly_id!(params[:id])
    if !current_user.is_favorite_of?(@job)
      current_user.favorite!(@job)
      flash[:notice] = "收藏成功，可以到我收藏的工作中查看。"
    else
      flash[:warning] = "此工作已收藏！"
    end
      redirect_to :back
  end

  def unfavorite
   @job = Job.find_by_friendly_id!(params[:id])
   if current_user.is_favorite_of?(@job)
     current_user.unfavorite!(@job)
     flash[:notice] = "已取消收藏"
   else
     flash[:warning] = "此工作未被收藏！"
   end
     redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :company, :category_id, :location_id, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")
    # 处理params[:q]拿到的资料，把特殊字符拿掉
    if params[:q].present?
      @search_criteria =  {
        title_or_company_or_location_name_cont: @query_string
      }
    end
  end

  # 告诉controller我们要找的资料范围
  def search_criteria(query_string)
    { :title_or_company_or_location_name_cont => query_string }
  end

end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/favorite/jobs_helper.rb
module Favorite::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  # 职位公开／隐匿图标显示
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end

  # 薪水区间 #
  def render_job_wage(job)
    "#{job.wage_lower_bound} k ~ #{job.wage_upper_bound} k"
  end

  # 判断是否投递过简历icon #
  def render_job_resumes(job)
    if job.resumes.count > 0
      "fa fa-envelope-open-o"
    else
      "fa fa-envelope-o"
    end
  end

  # 判断是否有人收藏icon #
  def render_job_collections(job)
    if job.job_favorites.count > 0
      "fa fa-heart"
    else
      "fa fa-heart-o"
    end
  end
end

app/views/jobs/_form.html.erb
<!--=== 工作列表 ===-->
<div class="row">
  <div class="col-md-9 col-xs-12 job-box">
    <!--=== 职位信息 ===-->
    <div class="col-md-6 col-xs-12 info">
      <div class="info-top">
        <h3><%= link_to(job.title, job_path(job), target: "_blank" )%></h3><span><%= job.created_at.strftime("%Y-%m-%d") %></span>
      </div>
      <div class="info-mid">
        <%= job.wage_lower_bound %> k ~ <%= job.wage_upper_bound %> k
      </div>
      <div class="info-bot">
        <span class="category"><span class="<%= job.category.icon %>"> <%= job.category.name %></span>
      </div>
    </div>

    <!--=== 公司信息 ===-->
    <div class="col-md-6 col-xs-12 company">
      <div class="company-top">
        <span><%= job.company %></span>
        <% if current_user && current_user.is_favorite_of?(job) %>
          <%= link_to unfavorite_job_path(job), method: :post do %><i class="fa fa-star" aria-hidden="true"></i><% end %>
        <% else %>
          <%= link_to favorites_job_path(job), method: :post do %><i class="fa fa-star-o" aria-hidden="true"></i><% end %>
        <% end %>
      </div>
      <div class="company-mid">
        <span class="fa fa-envelope"></span><span><%= job.contact_email %></span>
      </div>
      <div class="company-bot">
        <span class="fa fa-map-marker"></span><span><%= job.location.name %></span>
      </div>
    </div>
  </div>
</div>

app/views/jobs/_search_bar.html.erb
<div class="row">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2">
    <%= form_tag search_jobs_path , :method => :get, :class => "jobs-search-form" do %>
      <div class="input-group">
        <input type="text" class="form-control search-bar-input" name="q" value="<%= params[:q] %>" placeholder="职位，城市，公司">

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default search-bar-submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1>Edit a job</h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>

<% end %>

app/views/jobs/index.html.erb
<!-- ===职位筛选排序=== -->
<!-- <div class="dropdown clearfix pull-right">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      排序
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li>
          <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
        </li>
        <li>
            <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>

        </li>
        <li>
          <%= link_to("按照发表时间排序", jobs_path ) %>

        </li>
    </ul>
</div> -->

<!-- ===职位筛选排序=== -->
<div class="col-md-10 col-md-offset-1 job-content">
  <div class="row">
    <div class="col-md-12 btn-group select-job-box">
      <!--=== 工作地点下拉选单 ===-->
      <div class="dropdown btn-group clearfix">
        <% if params[:location].present? %>
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= params[:location] %> <span class="caret"></span>
        </button>
        <% else %>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          工作地点 <span class="caret"></span>
        </button>
        <% end %>
        <ul class="dropdown-menu" selection aria-labelledby="dropdownMenuDivider">
          <% @locations.each do |location| %>
          <li>
            <%= link_to(location.name, jobs_path(:location => location.name)) %>
          </li>
          <% end %>
          <li>
            <%= link_to("所有城市", jobs_path(:location => "所有城市") ) %>
          </li>
        </ul>
      </div>

      <!--=== 职位类型下拉选单 ===-->
      <div class="dropdown btn-group clearfix">
        <% if params[:category].present? %>
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= params[:category] %> <span class="caret"></span>
        </button>
        <% else %>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          职位类型 <span class="caret"></span>
        </button>
        <% end %>
        <ul class="dropdown-menu" selection aria-labelledby="dropdownMenuDivider">
          <% @categorys.each do |category| %>
          <li>
            <%= link_to(category.name, jobs_path(:category => category.name)) %>
          </li>
          <% end %>
          <li>
            <%= link_to("所有类型", jobs_path(:category => "所有类型") ) %>
          </li>
        </ul>
      </div>

      <!--=== 月薪下拉选单 ===-->
      <div class="dropdown btn-group clearfix">
        <% if params[:wage].present? %>
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= params[:wage] %> <span class="caret"></span>
        </button>
        <% else %>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          月薪 <span class="caret"></span>
        </button>
        <% end %>
        <ul class="dropdown-menu" selection aria-labelledby="dropdownMenuDivider">
          <li>
            <%= link_to("5k以下", jobs_path(:wage => "5k以下")) %>
          </li>
          <li>
            <%= link_to("5~10k", jobs_path(:wage => "5~10k")) %>
          </li>
          <li>
            <%= link_to("10~15k", jobs_path(:wage => "10~15k")) %>
          </li>
          <li>
            <%= link_to("15~25k", jobs_path(:wage => "15~25k")) %>
          </li>
          <li>
            <%= link_to("25k以上", jobs_path(:wage => "25k以上")) %>
          </li>
        </ul>
      </div>
    </div>
  </div>
<!-- ===职位筛选排序=== -->

<!--=== 工作列表 ===-->
<div class="row">
<% if @jobs.length > 0 %>
  <% @jobs.each do |job| %>
  <div class="col-md-9 col-xs-12 job-box" style="position:relative">
    <!--=== 职位信息 ===-->
    <div class="col-md-6 col-xs-12 info">
      <div class="info-top">
        <h3><%= link_to(job.title, job_path(job), target: "_blank" )%></h3><span><%= job.created_at.strftime("%Y-%m-%d") %></span>
      </div>
      <div class="info-mid">
        <%= job.wage_lower_bound %> k ~ <%= job.wage_upper_bound %> k
      </div>
      <div class="info-bot">
        <span class="category"><span class="<%= job.category.icon %>"> <%= job.category.name %></span>
      </div>
    </div>

    <!--=== 公司信息 ===-->
    <div class="col-md-6 col-xs-12 company">
      <div class="company-top">
        <span><%= job.company %></span>
        <% if current_user && current_user.is_favorite_of?(job) %>
          <%= link_to unfavorite_job_path(job), method: :post do %><i class="fa fa-star" aria-hidden="true"></i><% end %>
        <% else %>
          <%= link_to favorites_job_path(job), method: :post do %><i class="fa fa-star-o" aria-hidden="true"></i><% end %>
        <% end %>
      </div>
      <div class="company-mid">
        <span class="fa fa-envelope"></span><span class="color: #4A6BB5;font-size: 10px;"><%= job.contact_email %></span>
      </div>
      <div class="company-bot">
        <span class="fa fa-map-marker"></span><span><%= job.location.name %></span>
      </div>
    </div>
  </div>
  <% end %>
<% else %>
<!--=== 没有职位资料 ===-->
    <div class="col-md-9 col-xs-12 no-job-data">
      <h2 style="border-color:white">此分类暂时没有招聘职位哦，请尝试其他选项。</h2>
    </div>
<% end %>

<!--=== 职位推荐：随机推荐五个职位 ===-->
    <div class="col-md-2 side-box" style="position:absolute;top:30px">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-10 col-md-offset-1 suggest-title">
              <span class="fa fa-tags"></span> <span>职位推荐</span>
            </div>
            <div class="row">
            <% @suggests.each do |job| %>
            <div class="col-xs-10 col-xs-offset-1 suggest-content">
              <div>
                <h3>
                  <%= link_to job_path(job), target: "_blank" do %>
                    <%= job.title %> [<%= job.location.name %>]
                  <% end %>
                </h3>
              </div>
              <div><p><%= job.wage_lower_bound %> k ~ <%= job.wage_upper_bound %> k</p></div>
              <div><span><%= job.company %></span></div>
            </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--=== 分页区块 ===-->
<div class="col-md-10 col-md-offset-1 job-bottom">
  <div class="text-center">
    <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/jobs/new.html.erb
<h1>Add a job</h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>

<% end %>

app/views/jobs/show.html.erb
<!-- <h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>
  <span><span class="<%= @job.category.icon %>"> <%= @job.category.name %></span>
</p>

<div class="text-center">
  <%= link_to("投交履历", new_job_resume_path(@job), :style => "font-size: 30px; text-decoration:underline;") %>
</div> -->


<div class="job-content">
  <!--======== Start - Jobs上方区块 =========-->
  <div class="row">
    <!--======== Start - 左侧区块 =========-->
    <div class="col-md-7 col-md-offset-1 job-info-box">
      <h1><%= @job.title %><span class="company">  / <%= @job.company %></span></h1>
      <p>
        <span class="wage"><%= @job.wage_lower_bound %> k ~ <%= @job.wage_upper_bound %>  k </span> /
        <span><span class="fa fa-map-marker"></span> <%= @job.location.name %></span> /
        <span><span class="<%= @job.category.icon %>"> <%= @job.category.name %></span>
       </p>
      <p class="created"><%= @job.created_at.strftime("%Y-%m-%d") %> <span class="website">发布于招聘网</span></p>
    </div>
    <!--======== End - 左侧区块 =========-->

    <!--======== Start - 右侧区块 =========-->
    <div class="col-md-3 job-action-box">
      <div>
        <!--==== 判断是否已收藏 ====-->
        <% if current_user && current_user.is_favorite_of?(@job) %>
          <%= link_to unfavorite_job_path(@job), method: :post, class: "btn btn-lg btn-primary" do %>
            <span class="fa fa-star"></span> 已收藏
          <% end %>
        <% else %>
          <%= link_to favorites_job_path(@job), method: :post, class: "btn btn-lg btn-default" do %>
            <span class="fa fa-star-o"></span> 收藏
          <% end %>
        <% end %>
      </div>
      <div>
        <!--==== 判断是否已投过简历 ====-->
        <% if @resumes.length > 0 %>
          <%= link_to("已投过简历", '#', class: "btn btn-lg btn-danger") %>
        <% else %>
          <%= link_to("投递简历", new_job_resume_path(@job), class: "btn btn-lg btn-success") %>
        <% end %>
      </div>
    </div>
    <!--======== End - 右侧区块 =========-->
  </div>
  <!--======== End - Jobs上方区块 =========-->
<hr style="width:85%" />
  <!--======== Start - Jobs下方区块 =========-->
  <div class="row">
    <!--======== Start - 左侧区块 =========-->
    <div class="col-md-7 col-md-offset-1 job-content-box">
      <div class="content-info">
        <h4>职位描述：</h4>
        <p><%= markdown(@job.description) %></p>
      </div>
      <hr />
      <div class="mail-info">
        <h4>联络信息：</h4>
        <p class="email"><span class="fa fa-envelope"></span> <%= @job.contact_email %></p>
      </div>
    </div>

    <!--======== Start - 右侧区块 =========-->
    <% if @sames.length > 0 %>
    <div class="col-md-3">
      <div class="same-box">
        <div class="title">
          <span>相似职位</span>
        </div>
        <% @sames.each do |job| %>
          <div class="same-content">
            <div>
              <h3>
                <%= link_to job_path(job), target: "_blank" do %>
                  <%= job.title %>
                <% end %>
                <%= link_to job_path(job), target: "_blank" do %>
                  [<%= job.location.name %>]
                <% end %>
              </h3>
            </div>
            <div><p><%= job.wage_lower_bound %> k ~ <%= job.wage_upper_bound %> k</p></div>
            <div><span><%= job.company %></span></div>
          </div>
        <% end %>
      </div>
    </div>

    <% end %>
    <!--======== End - 左侧区块 =========-->

  </div>
  <!--======== End - Jobs下方区块 =========-->
</div>