config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
    resources :categories do

    end
    resources :locations
  end

  # 收藏／取消收藏工作
  resources :jobs do
    member do
      post :favorites #因与下面的favorite同名，出现routes错误，此处改名处理
      post :unfavorite
    end
    collection do
      get :search
    end
    resources :resumes
  end



  # 我收藏的工作
  namespace :favorite do #此处即为上面所说变量重名的问题
    resources :jobs
  end

  # 我的讨论组和我的文章
  namespace :account do
    resources :groups do
      resources :posts
    end
    resources :posts
    resources :resumes
    resources :votes
    resources :comments
  end

  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      # member do
        # post :upvote
        # post :downvote
      #   post "upvote" => "posts#upvote"
      #   post "downvote" => "posts#downvote"
      # end
      resources :comments do
        # member do
        #   post :like
        #   post :unlike
        # end
      end
    end
  end
  # resources :posts


  resources :posts do
    member do
      # post :upvote
      # post :downvote
      post "upvote" => "posts#upvote"
      post "downvote" => "posts#downvote"
    end
  end

  resources :comments do
    member do
      post :like
      post :unlike
    end
  end

  root 'welcome#index'
end

app/models/group.rb
class Group < ApplicationRecord
 mount_uploader :avatar, AvatarUploader
 validates :title, presence: true

 belongs_to :user
 has_many :posts

 # rails g model group_relationship group_id:integer user_id:integer
 # 参与的讨论群
 has_many :group_relationships
 # 一个讨论组包括成员
 has_many :members, through: :group_relationships, source: :user

end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  # 参与过的群组
  def index
    @groups = current_user.participated_groups.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy, :join, :quit]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @groups = Group.all.paginate(:page => params[:page], :per_page => 5)
    # @user = current_user
    # @groups = Group.where(:user_id => @user).order("created_at DESC").paginate(:page => params[:page], :per_page => 7)
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end


  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      # 创建之后自动加入
      current_user.join!(@group)
      redirect_to groups_path, notice: "讨论版块创建成功。"
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @group.update(group_params)
      redirect_to groups_path, notice: "讨论版块修改成功。"
    else
      render :edit
    end
  end

  def destroy

    @group.destroy
    redirect_to groups_path, alert: "讨论版块已删除，且不可恢复！"
  end

  def join
   @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      # 创建之后自动加入
      current_user.join!(@group)
      flash[:notice] = "加入本讨论版成功！"
    else
      flash[:warning] = "你已经是本讨论版成员了！"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "已退出本讨论版！"
    else
      flash[:warning] = "你不是本讨论版成员，怎么退出"
    end

    redirect_to group_path(@group)
  end

  private

  def find_group_and_check_permission
    @group = Group.find(params[:id])

    if current_user != @group.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def group_params
    params.require(:group).permit(:title, :description, :avatar)
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  # 自定义方法
  def render_group_description(group)
    simple_format(group.description)
  end

end

app/views/groups/_form.html.erb
<!-- ===Bootstrap表单开始=== -->
<!-- <%= form_for @group do |f| %>

  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
  <% end %>

<% end %> -->
<!-- ===Bootstrap表单开始=== -->


<div class="col-md-10 col-md-offset-1 job-form-content">
  <hr style="size:2px" />
  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, :label => false, placeholder: '请输入讨论组名称' %>
      <%= f.input :description, :label => false, placeholder: '请输入讨论组结束', input_html: { class: 'job-content-info' } %>
    </div>
    <div class="form-actions">
      <%= f.submit "创建", disable_with: "Submiting...", class: "button"%>
    </div>
  <% end %>
</div>

app/views/groups/_group_item.html.erb
<tr>
  <td> <%= link_to image_tag(group.avatar.url(:large)), group_path(group), :target => "_blank" %></td>
  <td><%= link_to(group.title, group_path(group)) %></td>
  <td><%= render_group_description(group) %></td>
  <td><%= group.group_relationships.count %></td>
  <td><%= group.posts.count %></td>
  <td> <%= group.user.username %> </td>
</tr>

app/views/groups/edit.html.erb
<div class="col-md-6 col-md-offset-3 job-setup">
  <div class="col-md-12 job-form-content">
    <h2><span class="fa fa-file-text-o"></span> 编辑讨论组</h2>
    <%= render('form') %>
  </div>
</div>

app/views/groups/index.html.erb
<!-- <% if @groups.length > 0 %>
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
        <td>count</td>
        <td>postcount</td>
        <td>Creator </td>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "group_item", :collection => @groups, :as => :group %>
    </tbody>
  </table>
</div>
<% else %> -->
<!--=== 没有职位资料 ===-->
    <!-- <div class="col-md-8 col-md-offset-2 no-job-data">
      <h2 style="border-color:white">暂时无人创建讨论版块，你可以成为第一个吃螃蟹的人。</h2>
      <p><%= link_to("立即创建", new_group_path, class: "btn btn-lg btn-success") %></p>
    </div>
<% end %> -->

<!--=== 分页区块 ===-->
<!-- <div class="col-md-10 col-md-offset-1 job-bottom">
  <div class="text-center">
    <%= will_paginate @groups, renderer: BootstrapPagination::Rails %>
  </div>
</div> -->
<div id="groups-list">
<div class="container-fluid groups-list">
  <div class="container">
    <div class="row" style="margin-bottom:20px">
      <div class="group col-md-8 col-md-offset-2">
        <p>
        <h1 class="pull-left" style="margin-top:0px">讨论列表</h1>
        <%= link_to("创建讨论", new_group_path, class: "btn btn-primary pull-right") %>
      </p>
      </div>
    <% @groups.each do |group| %>
    <div class="groups-list col-md-8 col-md-offset-2">
      <div class="media">
      <div class='box1'>
          <a class="pull-left"><%= link_to image_tag(group.avatar.url(:big)), group_path(group), :target => "_blank" %></a>
      </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to(group.title, group_path(group)) %></h4>
          <%= render_group_description(group) %>
        </div>
        <div class="icon">
          <a class="heart icon" style="color:orange;font-size:20px;margin-right:10px"> <i class="fa fa-user-circle"></i> <span style="font-size:15px;color:#999"><%= group.group_relationships.count %></span></a>
          <a class="star icon" style="color:orange;font-size:18px;"> <i class="fa fa-file"></i> <span style="font-size:15px;color:#999"><%= group.posts.count %></span></a>
        </div>
      </div>
      </div>
    <% end %>
  </div>
  </div>
</div>
</div>

<!--=== 分页区块 ===-->
<div class="col-md-10 col-md-offset-1 job-bottom">
  <div class="text-center">
    <%= will_paginate @groups, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="col-md-6 col-md-offset-3 job-setup">
  <div class="col-md-12 job-form-content">
    <h2><span class="fa fa-file-text-o"></span> 新增讨论组</h2>
    <%= render('form') %>
  </div>
</div>

app/views/groups/show.html.erb
<!-- <div class="col-md-12">
  <div class="group" style="margin-top:20px">
    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@group) %>
        <label class="label label-success"> 群组成员 </label>
            <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning"> 不是群组成员 </label>
            <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>
      <% if current_user && current_user.is_member_of?(@group) %>
      <%= link_to("Write a Post", new_group_post_path(@group), class: "btn btn-default pull-right")%>
      <% end %>
  </div>
  </br>
  <h2 style="border-color:white"><%= @group.title %>
  <% if current_user && current_user == @group.user %>
    <%= link_to(edit_group_path(@group), class: "btn btn-md btn-default") do %>
      <span class="fa fa-pencil"></span>
    <% end %>
    <%= link_to(group_path(@group),  class: "btn btn-md btn-default", :method => :delete, :data => { :confirm => "你确定要删除改讨论版块吗？" }) do %>
      <span class="fa fa-trash"></span>
    <% end %>
  <% end %>
  </h2>
  <p><%= @group.description %></p>
<% if @posts.length > 0 %>
<div class="col-md-12">
   <table class="table">
     <thead>
      <tr>
         <th>文章标题</th>
         <th>发表者</th>
         <th>发表时间</th>
         <th>访问量</th>
         <th>点赞量</th>
         <th>评论数</th>
       </tr>
     </thead>
     <tbody>
       <% @posts.each do |post| %>
         <tr>
           <td><%= link_to(post.title, group_post_path(post)) %></td>
           <td><%= post.user.email %></td>
           <td><%= post.created_at.strftime('%Y-%m-%d')%></td>
           <td><%= "#{post.impressionist_count(:filter=>:session_hash)}" %></td>
           <td><%= post.voters.count %></td>
           <td><%= post.comments.count %></td>
         </tr>
       <% end %>
     </tbody>
   </table>
</div>
<% else %> -->
<!--=== 没有职位资料 ===-->
    <!-- <div class="col-md-8 col-md-offset-2 no-job-data">
      <h2 style="border-color:white">暂时无人发布，你可以成为第一个发布的人。</h2>
      <p><%= link_to("立即创建", new_group_post_path(@group), class: "btn btn-lg btn-success") %></p>
    </div>
<% end %>
</div> -->
<!--=== 分页区块 ===-->
<!-- <div class="col-md-10 col-md-offset-1 job-bottom">
  <div class="text-center">
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div> -->
<div id="group-show">
<div class="container-fluid group-show">
			<div class="container">
				<div class="row">
					<div class=" col-md-12 email">
						<div class="media">
							<div class="box1">
              <a class="pull-left"><%= link_to image_tag(@group.avatar.url(:big)), group_path(@group), :target => "_blank" %></a>
							</div>
							<div class="media-body">
								<h4 class="media-heading" style="font-size:22px;color:#212121"><%= link_to(@group.title, group_path(@group)) %>
									<a>
                    <% if current_user && current_user.is_member_of?(@group) %>
                      <!-- <label class="label label-success"> 群组成员 </label> -->
                          <%= link_to("退出讨论", quit_group_path(@group), method: :post, class: "btn btn-default") %>
                    <% else %>
                      <!-- <label class="label label-warning"> 不是群组成员 </label> -->
                          <%= link_to("加入讨论", join_group_path(@group), method: :post, class: "btn btn-danger") %>
                    <% end %>
									</a>
									<a class="heart font"> <span style="color:#aaa;font-size:12px">关注:</span>   <span style="color:#ff7f3e"><%= @group.group_relationships.count %></span></a>
									<a class="heart font"> <span style="color:#aaa;font-size:12px">文章:</span>   <span style="color:#ff7f3e"><%= @group.posts.count %></span></a>
	                  <% if current_user && current_user.is_member_of?(@group) %>
	                  <%= link_to("发布文章", new_group_post_path(@group), class: "btn btn-warning pull-right") %>
                  <% end %>
									<div class="update">
                    <% if current_user && current_user == @group.user %>
                      <%= link_to(edit_group_path(@group), class: "btn btn-md btn-default") do %>
                        <span class="fa fa-cogs"></span>
                      <% end %>
                      <%= link_to(group_path(@group),  class: "btn btn-md btn-default", :method => :delete, :data => { :confirm => "你确定要删除改讨论版块吗？" }) do %>
                        <span class="fa fa-trash"></span>
                      <% end %>
                    <% end %>
								</h4>
								<span style="font-size:14px"><%= render_group_description(@group) %></span>
							</div>
						</div>
					</div>

				</div>

				<!--打卡-->
				<div class="row ">
          <% if @posts.length > 0 %>
          <% @posts.each do |post| %>
					<div class="col-md-10 col-md-offset-1">
						<div class="thumbnail">
							<div class="caption" style="font-size:18px">
								<h3><%= link_to(post.title, group_post_path(post)) %></h3>
								<p style="color:grey;font-size:13px">
									作者：<span class="author"><%= post.user.username %></span>
									时间：<span class="time"><%= post.created_at.strftime('%Y-%m-%d %H:%M:%S')%></span>
								</p>
								<p><%= truncate(strip_tags(raw(post.content)),:length=>60) %></p>
								<p>
									<a class="heart icon" style="color:grey"> <i class="fa fa-eye"></i>
                    <span><%= "#{post.impressionist_count(:filter=>:session_hash)}" %></span>
                  </a>
									<a class="apple icon" style="color:grey"> <i class="fa fa-thumbs-up"></i>
                    <span><%= post.voters.count %></span>
                  </a>
								  <a class="star icon" style="color:grey"> <i class="fa fa-heart"></i>
                    <span><%= post.comments.count %></span>
                  </a>
								</p>
							</div>
						</div>
					</div>
          <% end %>
          <% else %>
              <div class="col-md-8 col-md-offset-2 no-job-data">
                <h2 style="border-color:white">暂时无人发布，你可以成为第一个发布的人。</h2>
                <p><%= link_to("立即创建", new_group_post_path(@group), class: "btn btn-lg btn-success") %></p>
              </div>
          <% end %>
          </div>
				</div>
			</div>
			<!--=== 分页区块 ===-->
			<div class="col-md-10 col-md-offset-1 job-bottom">
			  <div class="text-center">
			    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
			  </div>
			</div>
</div>