config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
    resources :categories do

    end
    resources :locations
  end

  # 收藏／取消收藏工作
  resources :jobs do
    member do
      post :favorites #因与下面的favorite同名，出现routes错误，此处改名处理
      post :unfavorite
    end
    collection do
      get :search
    end
    resources :resumes
  end



  # 我收藏的工作
  namespace :favorite do #此处即为上面所说变量重名的问题
    resources :jobs
  end

  # 我的讨论组和我的文章
  namespace :account do
    resources :groups do
      resources :posts
    end
    resources :posts
    resources :resumes
    resources :votes
    resources :comments
  end

  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      # member do
        # post :upvote
        # post :downvote
      #   post "upvote" => "posts#upvote"
      #   post "downvote" => "posts#downvote"
      # end
      resources :comments do
        # member do
        #   post :like
        #   post :unlike
        # end
      end
    end
  end
  # resources :posts


  resources :posts do
    member do
      # post :upvote
      # post :downvote
      post "upvote" => "posts#upvote"
      post "downvote" => "posts#downvote"
    end
  end

  resources :comments do
    member do
      post :like
      post :unlike
    end
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: { message: "请输入类型名称" }
  validates :icon, presence: { message: "请输入ICON代码" }

  has_many :jobs

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes
  has_many :likers, through: :likes, source: :user
end

app/models/group.rb
class Group < ApplicationRecord
 mount_uploader :avatar, AvatarUploader
 validates :title, presence: true

 belongs_to :user
 has_many :posts

 # rails g model group_relationship group_id:integer user_id:integer
 # 参与的讨论群
 has_many :group_relationships
 # 一个讨论组包括成员
 has_many :members, through: :group_relationships, source: :user

end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
  # 标题不能为空
  validates :title, presence: true
  #薪资不能为空，最低底薪大于0
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
  # 重构重复代码／公开
  scope :published, -> { where(is_hidden: false) }
  # 自动查找5个职位数据
  scope :random5, -> { limit(5).order("RANDOM()") }
  # 重构重复代码／最近排序
  scope :recent, -> { order('created_at DESC') }
  scope :wage1, -> { where('wage_lower_bound <= 5 or wage_upper_bound <= 5') }
  scope :wage2, -> { where('wage_lower_bound between 5 and 10 or wage_upper_bound between 5 and 10') }
  scope :wage3, -> { where('wage_lower_bound between 10 and 15 or wage_upper_bound between 10 and 15') }
  scope :wage4, -> { where('wage_lower_bound between 15 and 25 or wage_upper_bound between 15 and 25') }
  scope :wage5, -> { where('wage_lower_bound >= 25 or wage_upper_bound >= 25') }

  # has_many :resumes
  has_many :resumes, dependent: :destroy

  # 收藏职位
  has_many :job_favorites
  has_many :collectors, through: :job_favorites, source: :user

  belongs_to :user
  # 职位类别
  belongs_to :category

  # 工作地点
  belongs_to :location

  # 公开职位
  def publish!
    self.is_hidden = false
    self.save
  end

  # 隐匿职位
  def hide!
    self.is_hidden = true
    self.save
  end

  before_validation :generate_friendly_id, :on => :create

  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end

end

app/models/job_favorite.rb
class JobFavorite < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord

  validates :name, presence: { message: "请输入工作地点" }

  has_many :jobs
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  # 统计访问量
  is_impressionable
  belongs_to :user
  belongs_to :group
  # has_many :votes
  has_many :votes, :dependent => :destroy
  has_many :voters, through: :votes, source: :user

  #是否已经点过赞
  def find_vote(user)
    self.votes.where( :user_id => user.id ).first
  end

  # 留言
  has_many :comments

  # 重构重复代码／最近排序
  scope :recent, -> { order('created_at DESC') }

end

app/models/resume.rb
class Resume < ApplicationRecord
  validates :content, presence: { message: "请填写简历描述" }
  validates :attachment, presence: { message: "请选择简历文档" }
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  # validates :content, presence: true
  scope :recent, -> { order('created_at DESC') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :resumes
  has_many :groups
  has_many :posts
  has_many :jobs
  # has_many :votes
  has_many :votes, :dependent => :destroy
  has_many :voted_posts, :through => :votes, :source => :post

  # 参与讨论组
  has_many :group_relationships
  has_many :participated_groups, :through => :group_relationships, :source => :group

  # 收藏职位
  has_many :job_favorites
  has_many :favorite_jobs, through: :job_favorites, source: :job

  #留言
  # has_many :comments

  #点赞
  has_many :likes
  has_many :liked_comments, :through => :likes, :source => :comment

  # 是否为管理员
  # 判断数据库中的管理员栏位的布尔值
  def admin?
    is_admin
  end

  def website_admin?
    is_website_admin
  end

  # 是否已收藏职位
  def is_favorite_of?(job)
    favorite_jobs.include?(job)
  end

  # 收藏职位
  def favorite!(job)
    favorite_jobs << job
  end

  # 取消收藏职位
  def unfavorite!(job)
    favorite_jobs.delete(job)
  end

  # 是否为群组里的一员？
  def is_member_of?(group)
    participated_groups.include?(group)
  end

  # 加入群组
  def join!(group)
    participated_groups << group
  end

  # 退出群组
  def quit!(group)
    participated_groups.delete(group)
  end

  #  是否投递过
  def is_upload_of?(job)
    resumes.include?(job)
  end

  # 是否点赞过
  # def is_voter_of?(post)
  #  voted_posts.include?(post)
  # end

  # 点赞
  # def upvote!(post)
  #   voted_posts << post
  # end

  # 取消点赞
  # def downvote!(post)
  #   voted_posts.delete(post)
  # end

  # 是否喜欢过
  def is_liker_of?(comment)
  liked_comments.include?(comment)
  end

  # 点赞
  def like!(comment)
    liked_comments << comment
  end

  # 取消点赞
  def unlike!(comment)
    liked_comments.delete(comment)
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # 自定义方法
  def render_group_description(group)
    simple_format(group.description)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper

  # 职位公开／隐匿图标显示
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end

  # 薪水区间 #
  def render_job_wage(job)
    "#{job.wage_lower_bound} k ~ #{job.wage_upper_bound} k"
  end

  # 判断是否投递过简历icon #
  def render_job_resumes(job)
    if job.resumes.count > 0
      "fa fa-envelope-open-o"
    else
      "fa fa-envelope-o"
    end
  end

  # 判断是否有人收藏icon #
  def render_job_collections(job)
    if job.job_favorites.count > 0
      "fa fa-heart"
    else
      "fa fa-heart-o"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<!-- ===flash功能样式=== -->
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="row">
                <div class="col-md-2 col-xs-4">
                  <h4>工作机会</h4>
                  <ul class="list-unstyled">
                    <li><a href="#s">职位搜索</a></li>
                    <li><a href="#s">新闻资讯</a></li>
                    <li><a href="#s">服务热线</a></li>
                  </ul>
                </div>
                <div class="col-md-2 col-xs-4">
                  <h4>企业资源</h4>
                  <ul class="list-unstyled">
                    <li><a href="#s">企业培训</a></li>
                    <li><a href="#s">联合活动</a></li>
                    <li><a href="#s">专属服务</a></li>
                  </ul>
                </div>
                <div class="col-md-2 col-xs-4">
                  <h4>关于我们</h4>
                  <ul class="list-unstyled">
                    <li><a href="#s">公司介绍</a></li>
                    <li><a href="#s">常见问题</a></li>
                    <li><a href="#s">联系方式</a></li>
                  </ul>
                </div>
                <div class="col-md-6 col-xs-12 footer-box">
                  <div>
                    <a href="#s"><%= image_tag("link_facebook.png") %></a>
                    <a href="#s"><%= image_tag("link_google-plus.png") %></a>
                    <a href="#s"><%= image_tag("link_linkedin.png") %></a>
                    <a href="#s"><%= image_tag("link_twitter.png") %></a>
                  </div>
                  <div class="footer-content">
                    <%= image_tag("wechat.png") %> WeChat
                    <%= image_tag("QQ.png") %> QQ <br />
                    <%= image_tag("github.png") %> https://github.com/sishuai0328
                    <div class="goodjob">
                      <a href="" target="_blank"><%= image_tag("thumbs-up.png") %></a>
                    </div>
                  </div>
                </div>
              </div>
                <hr />
                <p>Designed By <a href="https://github.com/sishuai0328/job-recruitment" target="_blank">SISH</a> | Copyright ©2018 JobRecruitment
            </div>
        </div>
    </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="col-md-10 col-md-offset-1 container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->

        <!-- ===logo开始=== -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/" ><i aria-hidden="true"><strong>Job Recruitment </strong></i></a>
        </div>
        <!-- ===logo结束=== -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!-- ===搜索框开始=== -->
            <ul class="nav navbar-nav navbar-left">
                        <li><%= link_to("首页", root_path, class: "scroll") %></li>
                        <li><%= link_to("工作", jobs_path, class: "scroll") %></li>
                        <li><%= link_to("交流", groups_path, class: "scroll") %></li>
            </ul>

            <ul class="nav navbar-nav">
              <li>
                  <div class="form-group form-inline search-bar">
                    <%= render :partial => "jobs/search_bar"%>
                 </div>
                </li>
            </ul>
            <!-- ===搜索框结束=== -->
            <!-- ===账号操作开始=== -->
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                   <li><a href="#" data-toggle="modal" data-target="#signup-modal">注册</a></li>
                   <li><a href="#" data-toggle="modal" data-target="#login-modal">登录</a></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.username %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">

                        <li> <%= link_to("后台管理", admin_jobs_path) %> </li>
                        <li class="divider"> </li>
                        <li> <%= link_to("我点赞的文章", account_votes_path) %></li>
                        <li> <%= link_to("我的讨论", account_groups_path) %></li>
                        <li> <%= link_to("我的留言", account_comments_path) %></li>
                        <li> <%= link_to("我的文章", account_posts_path) %></li>
                        <li> <%= link_to("收藏职位", favorite_jobs_path) %> </li>
                        <li> <%= link_to("投递历史", account_resumes_path) %> </li>
                        <li class="divider"> </li>
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>

                    </ul>
                  </li>
                <% end %>
            </ul>
            <!-- ===账号操作结束=== -->
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>




<!-- ===登录弹窗开始=== -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2><span class="fa fa-sign-in"></span> 帐号登录</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email, :label => false, placeholder: '邮箱', required: false, autofocus: true %>
        <%= f.input :password, :label => false, placeholder: '密码', required: false %>
        <%= f.input :remember_me, :label => "记住我", as: :boolean if devise_mapping.rememberable? %>
        <%= link_to "忘记密码？", new_password_path(resource_name), class: "psw" %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "登录",class: "button" %>
         </div>
       <% end %>
       <hr />
      <div class="account">
        <%= link_to "没有帐号，立即注册", new_registration_path(resource_name) %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2><span class="fa fa-user-circle-o"></span> 帐号注册</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email, :label => false, placeholder: '请输入常用的邮箱地址', error: '请输入邮箱地址', required: true, autofocus: true %>
          <%= f.input :username, :label => false, placeholder: '请输入真实姓名', error: '请输入姓名', required: true %>
          <%= f.input :is_admin, :label => false, as: :radio_buttons, collection:  [['个人用户', false], ['企业用户', true]], required: true %>
          <%= f.input :password, :label => false, placeholder: '请输入6-16位密码', error: '请输入6-16位密码', required: true, input_html: { maxlength: 16 } %>
       <%= f.input :password_confirmation, :label => false, placeholder: '确认密码', error: '请输入相同的密码', required: true, input_html: { maxlength: 16 } %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "注册",class: "button" %>
        </div>
      <% end %>
      <hr />
      <div class="account">
        <%= link_to "已有帐号，立即登录", new_session_path(resource_name) %><br />
      </div>
    </div>
  </div>
</div>
<!-- ===登录弹窗结束=== -->